#PERSON
new_person:
  path: /person
  methods:
    - POST
  controller: App\Controller\PersonController::create
update_person:
  path: /person/{id}
  methods:
    - PUT
  controller: App\Controller\PersonController::update
delete_person:
  path: /person/{id}
  methods:
    - DELETE
  controller: App\Controller\PersonController::delete
persons:
  path: /persons
  methods:
    - GET
  controller: App\Controller\PersonController::findByAll
person:
  path: /person/{id}
  methods:
    - GET
  controller: App\Controller\PersonController::findById

#WORKOUTS
new_workouts:
  path: /workout
  methods:
    - POST
  controller: App\Controller\WorkoutsController::create
update_workouts:
  path: /workout/{id}
  methods:
    - PUT
  controller: App\Controller\WorkoutsController::update
delete_workouts:
  path: /workout/{id}
  methods:
    - DELETE
  controller: App\Controller\WorkoutsController::delete
workouts:
  path: /workouts
  methods:
    - GET
  controller: App\Controller\WorkoutsController::findByAll
workout:
  path: /workout/{id}
  methods:
    - GET
  controller: App\Controller\WorkoutsController::findById
workout_findByPersonWorkout:
  path: person/workout/{id}
  methods:
    - GET
  controller: App\Controller\WorkoutsController::findByPersonWorkout

#CHECK-WORKOUTS
new_checkworkouts:
  path: /checkworkout
  methods:
    - POST
  controller: App\Controller\CheckWorkoutsController::create
update_checkworkouts:
  path: /checkworkout/{id}
  methods:
    - PUT
  controller: App\Controller\CheckWorkoutsController::update
delete_checkworkouts:
  path: /checkworkout/{id}
  methods:
    - DELETE
  controller: App\Controller\CheckWorkoutsController::delete
checkworkouts:
  path: /checkworkouts
  methods:
    - GET
  controller: App\Controller\CheckWorkoutsController::findByAll
checkworkout:
  path: /checkworkout/{id}
  methods:
    - GET
  controller: App\Controller\CheckWorkoutsController::findById
checkworkout_person:
  path: /checkworkout/person/{id}
  methods:
    - GET
  controller: App\Controller\CheckWorkoutsController::findbyPersonWorkouts

#person user
person_user:
  path: /person/user
  methods:
    - POST
  controller: App\Controller\PersonUserController::create
#COMMENTS
new_workouts_comments:
  path: /workout/comments
  methods:
    - POST
  controller: App\Controller\CommentsController::create
update_workouts_comments:
  path: /workout/comments/{id}
  methods:
    - PUT
  controller: App\Controller\CommentsController::update
delete_workouts_comments:
  path: /workout/comments/{id}
  methods:
    - DELETE
  controller: App\Controller\CommentsController::delete
workouts_comments:
  path: /workouts/comments
  methods:
    - GET
  controller: App\Controller\CommentsController::findByAll
workout_comments:
  path: /workout/comments/{id}
  methods:
    - GET
  controller: App\Controller\CommentsController::findById
#user
new_user:
  path: /user
  methods:
    - POST
  controller: App\Controller\UserController::create
update_user:
    path: /user/{id}
    methods:
      - PUT
    controller: App\Controller\UserController::update
remove_user:
  path: /user/{id}
  methods:
    - DELETE
  controller: App\Controller\UserController::delete
findbyid_user:
  path: /user/{id}
  methods:
    - GET
  controller: App\Controller\UserController::findById
findbyall_user:
  path: /users
  methods:
    - GET
  controller: App\Controller\UserController::findByAll

# Auth
login:
  path: /login
  methods:
    - POST
  controller: App\Controller\AuthController::getToken